// <auto-generated />
namespace ShortRent.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class 更改权限表 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(更改权限表));
        
        string IMigrationMetadata.Id
        {
            get { return "201904071538598_更改权限表"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
