//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShortRent.Resource.HumanData {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HumanInfoChina {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HumanInfoChina() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShortRent.Resource.HumanData.HumanInfoChina", typeof(HumanInfoChina).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        public static string IconHumanContent {
            get {
                return ResourceManager.GetString("IconHumanContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string IconHumanID {
            get {
                return ResourceManager.GetString("IconHumanID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前缀 的本地化字符串。
        /// </summary>
        public static string IconHumanPrefix {
            get {
                return ResourceManager.GetString("IconHumanPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类目录 的本地化字符串。
        /// </summary>
        public static string LogHumanModelCatalogue {
            get {
                return ResourceManager.GetString("LogHumanModelCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string LogHumanModelCreateTime {
            get {
                return ResourceManager.GetString("LogHumanModelCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常详情 的本地化字符串。
        /// </summary>
        public static string LogHumanModelException {
            get {
                return ResourceManager.GetString("LogHumanModelException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string LogHumanModelID {
            get {
                return ResourceManager.GetString("LogHumanModelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器名称 的本地化字符串。
        /// </summary>
        public static string LogHumanModelMachineName {
            get {
                return ResourceManager.GetString("LogHumanModelMachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误信息 的本地化字符串。
        /// </summary>
        public static string LogHumanModelMessage {
            get {
                return ResourceManager.GetString("LogHumanModelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法全名 的本地化字符串。
        /// </summary>
        public static string LogHumanModelMethodFullName {
            get {
                return ResourceManager.GetString("LogHumanModelMethodFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程ID 的本地化字符串。
        /// </summary>
        public static string LogHumanModelProcessId {
            get {
                return ResourceManager.GetString("LogHumanModelProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程名称 的本地化字符串。
        /// </summary>
        public static string LogHumanModelProcessName {
            get {
                return ResourceManager.GetString("LogHumanModelProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 堆栈信息 的本地化字符串。
        /// </summary>
        public static string LogHumanModelStachTrace {
            get {
                return ResourceManager.GetString("LogHumanModelStachTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线程ID 的本地化字符串。
        /// </summary>
        public static string LogHumanModelThreadId {
            get {
                return ResourceManager.GetString("LogHumanModelThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法 的本地化字符串。
        /// </summary>
        public static string ManagerHumanModelActionName {
            get {
                return ResourceManager.GetString("ManagerHumanModelActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string ManagerHumanModelActivity {
            get {
                return ResourceManager.GetString("ManagerHumanModelActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标Class 的本地化字符串。
        /// </summary>
        public static string ManagerHumanModelClassIcons {
            get {
                return ResourceManager.GetString("ManagerHumanModelClassIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标颜色 的本地化字符串。
        /// </summary>
        public static string ManagerHumanModelColor {
            get {
                return ResourceManager.GetString("ManagerHumanModelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器 的本地化字符串。
        /// </summary>
        public static string ManagerHumanModelControllerName {
            get {
                return ResourceManager.GetString("ManagerHumanModelControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string ManagerHumanModelID {
            get {
                return ResourceManager.GetString("ManagerHumanModelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单名称 的本地化字符串。
        /// </summary>
        public static string ManagerHumanModelName {
            get {
                return ResourceManager.GetString("ManagerHumanModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父级名称 的本地化字符串。
        /// </summary>
        public static string ManagerHumanModelPidName {
            get {
                return ResourceManager.GetString("ManagerHumanModelPidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string PerOrComIntroGuidanceHumanModelCreateTime {
            get {
                return ResourceManager.GetString("PerOrComIntroGuidanceHumanModelCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库编号 的本地化字符串。
        /// </summary>
        public static string PerOrComIntroGuidanceHumanModelID {
            get {
                return ResourceManager.GetString("PerOrComIntroGuidanceHumanModelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 介绍问题内容 的本地化字符串。
        /// </summary>
        public static string PerOrComIntroGuidanceHumanModelQuestionMsg {
            get {
                return ResourceManager.GetString("PerOrComIntroGuidanceHumanModelQuestionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问题类型 的本地化字符串。
        /// </summary>
        public static string PerOrComIntroGuidanceHumanModelType {
            get {
                return ResourceManager.GetString("PerOrComIntroGuidanceHumanModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string PersonAdminHumanEditModelCreateTime {
            get {
                return ResourceManager.GetString("PersonAdminHumanEditModelCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string PersonAdminHumanEditModelID {
            get {
                return ResourceManager.GetString("PersonAdminHumanEditModelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台用户名 的本地化字符串。
        /// </summary>
        public static string PersonAdminHumanEditModelName {
            get {
                return ResourceManager.GetString("PersonAdminHumanEditModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string PersonAdminHumanEditModelPassWord {
            get {
                return ResourceManager.GetString("PersonAdminHumanEditModelPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户图片路径 的本地化字符串。
        /// </summary>
        public static string PersonAdminHumanEditModelPerImage {
            get {
                return ResourceManager.GetString("PersonAdminHumanEditModelPerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职位详情 的本地化字符串。
        /// </summary>
        public static string PersonAdminHumanEditModelPersonDetail {
            get {
                return ResourceManager.GetString("PersonAdminHumanEditModelPersonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职位 的本地化字符串。
        /// </summary>
        public static string PersonAdminHumanEditModelPosition {
            get {
                return ResourceManager.GetString("PersonAdminHumanEditModelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ 的本地化字符串。
        /// </summary>
        public static string PersonAdminHumanEditModelQq {
            get {
                return ResourceManager.GetString("PersonAdminHumanEditModelQq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微信 的本地化字符串。
        /// </summary>
        public static string PersonAdminHumanEditModelWeChat {
            get {
                return ResourceManager.GetString("PersonAdminHumanEditModelWeChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签颜色 的本地化字符串。
        /// </summary>
        public static string PublishTagsHumanModelColor {
            get {
                return ResourceManager.GetString("PublishTagsHumanModelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string PublishTagsHumanModelCreateTime {
            get {
                return ResourceManager.GetString("PublishTagsHumanModelCreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string PublishTagsHumanModelID {
            get {
                return ResourceManager.GetString("PublishTagsHumanModelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签名称 的本地化字符串。
        /// </summary>
        public static string PublishTagsHumanModelName {
            get {
                return ResourceManager.GetString("PublishTagsHumanModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顺序等级 的本地化字符串。
        /// </summary>
        public static string PublishTagsHumanModelTagOrder {
            get {
                return ResourceManager.GetString("PublishTagsHumanModelTagOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库编号 的本地化字符串。
        /// </summary>
        public static string RoleHumanModelID {
            get {
                return ResourceManager.GetString("RoleHumanModelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名称 的本地化字符串。
        /// </summary>
        public static string RoleHumanModelName {
            get {
                return ResourceManager.GetString("RoleHumanModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户类型 的本地化字符串。
        /// </summary>
        public static string RoleHumanModelType {
            get {
                return ResourceManager.GetString("RoleHumanModelType", resourceCulture);
            }
        }
    }
}
