//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShortRent.Resource.MetaData {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShortRent.Resource.MetaData.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName}必须大于或等于{ComparisonValue} 的本地化字符串。
        /// </summary>
        public static string greaterthanorequal_error {
            get {
                return ResourceManager.GetString("greaterthanorequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string HistoryOperatorDetailCreateTimeDisplayName {
            get {
                return ResourceManager.GetString("HistoryOperatorDetailCreateTimeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细描述 的本地化字符串。
        /// </summary>
        public static string HistoryOperatorDetailDetailDescirptionDisplayName {
            get {
                return ResourceManager.GetString("HistoryOperatorDetailDetailDescirptionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块名称 的本地化字符串。
        /// </summary>
        public static string HistoryOperatorDetailEntityModuleDisplayName {
            get {
                return ResourceManager.GetString("HistoryOperatorDetailEntityModuleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 具体操作 的本地化字符串。
        /// </summary>
        public static string HistoryOperatorDetailOperatesDisplayName {
            get {
                return ResourceManager.GetString("HistoryOperatorDetailOperatesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作人 的本地化字符串。
        /// </summary>
        public static string HistoryOperatorDetailpNameDisplayName {
            get {
                return ResourceManager.GetString("HistoryOperatorDetailpNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        public static string IconViewModelContentDisplayName {
            get {
                return ResourceManager.GetString("IconViewModelContentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string IconViewModelIDDisplayName {
            get {
                return ResourceManager.GetString("IconViewModelIDDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前缀 的本地化字符串。
        /// </summary>
        public static string IconViewModelPrefixDisplayName {
            get {
                return ResourceManager.GetString("IconViewModelPrefixDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName}必须在{From}和{To}之间 的本地化字符串。
        /// </summary>
        public static string inclusivebetween_error {
            get {
                return ResourceManager.GetString("inclusivebetween_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的用户名或密码 的本地化字符串。
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName}的长度必须是{MinLength}-{MaxLength}个字符 的本地化字符串。
        /// </summary>
        public static string length_error {
            get {
                return ResourceManager.GetString("length_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName}必须小于{ComparisonValue} 的本地化字符串。
        /// </summary>
        public static string lessthan_error {
            get {
                return ResourceManager.GetString("lessthan_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName}必须小于或等于{ComparisonValue} 的本地化字符串。
        /// </summary>
        public static string lessthanorequal_error {
            get {
                return ResourceManager.GetString("lessthanorequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法 的本地化字符串。
        /// </summary>
        public static string ManagerCreteModelActionNameDisplayName {
            get {
                return ResourceManager.GetString("ManagerCreteModelActionNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string ManagerCreteModelActivityDisplayName {
            get {
                return ResourceManager.GetString("ManagerCreteModelActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标类别 的本地化字符串。
        /// </summary>
        public static string ManagerCreteModelClassIconsDisplayName {
            get {
                return ResourceManager.GetString("ManagerCreteModelClassIconsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标颜色 的本地化字符串。
        /// </summary>
        public static string ManagerCreteModelColorDisplayName {
            get {
                return ResourceManager.GetString("ManagerCreteModelColorDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器 的本地化字符串。
        /// </summary>
        public static string ManagerCreteModelControllerNameDisplayName {
            get {
                return ResourceManager.GetString("ManagerCreteModelControllerNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单名称 的本地化字符串。
        /// </summary>
        public static string ManagerCreteModelNameDisplayName {
            get {
                return ResourceManager.GetString("ManagerCreteModelNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父级列表 的本地化字符串。
        /// </summary>
        public static string ManagerCreteModelPidDisplayName {
            get {
                return ResourceManager.GetString("ManagerCreteModelPidDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName}不能为空 的本地化字符串。
        /// </summary>
        public static string notempty_error {
            get {
                return ResourceManager.GetString("notempty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName}不能与{PropertyValue}相同 的本地化字符串。
        /// </summary>
        public static string notequal_error {
            get {
                return ResourceManager.GetString("notequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName}不能为空 的本地化字符串。
        /// </summary>
        public static string notnull_error {
            get {
                return ResourceManager.GetString("notnull_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string PassWordEditModelConfirmPassWordDisplayName {
            get {
                return ResourceManager.GetString("PassWordEditModelConfirmPassWordDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string PassWordEditModelIDDisplayName {
            get {
                return ResourceManager.GetString("PassWordEditModelIDDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧密码 的本地化字符串。
        /// </summary>
        public static string PassWordEditModelOldPassWordDisplayName {
            get {
                return ResourceManager.GetString("PassWordEditModelOldPassWordDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string PassWordEditModelPassWordDisplayName {
            get {
                return ResourceManager.GetString("PassWordEditModelPassWordDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string PerOrComIntroGuidanceViewModelIDDisplayName {
            get {
                return ResourceManager.GetString("PerOrComIntroGuidanceViewModelIDDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 介绍问题内容 的本地化字符串。
        /// </summary>
        public static string PerOrComIntroGuidanceViewModelQuestionMsgDisplayName {
            get {
                return ResourceManager.GetString("PerOrComIntroGuidanceViewModelQuestionMsgDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问题针对人 的本地化字符串。
        /// </summary>
        public static string PerOrComIntroGuidanceViewModelTypeDisplayName {
            get {
                return ResourceManager.GetString("PerOrComIntroGuidanceViewModelTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string PersonAdminEditModelIDDisplayName {
            get {
                return ResourceManager.GetString("PersonAdminEditModelIDDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string PersonAdminEditModelNameDisplayName {
            get {
                return ResourceManager.GetString("PersonAdminEditModelNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string PersonAdminEditModelPassWordDisplayName {
            get {
                return ResourceManager.GetString("PersonAdminEditModelPassWordDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头像 的本地化字符串。
        /// </summary>
        public static string PersonAdminEditModelPerImageDisplayName {
            get {
                return ResourceManager.GetString("PersonAdminEditModelPerImageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职位描述 的本地化字符串。
        /// </summary>
        public static string PersonAdminEditModelPersonDetailDisplayName {
            get {
                return ResourceManager.GetString("PersonAdminEditModelPersonDetailDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职位 的本地化字符串。
        /// </summary>
        public static string PersonAdminEditModelPositionDisplayName {
            get {
                return ResourceManager.GetString("PersonAdminEditModelPositionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ 的本地化字符串。
        /// </summary>
        public static string PersonAdminEditModelQqDisplayName {
            get {
                return ResourceManager.GetString("PersonAdminEditModelQqDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微信 的本地化字符串。
        /// </summary>
        public static string PersonAdminEditModelWeChatDisplayName {
            get {
                return ResourceManager.GetString("PersonAdminEditModelWeChatDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出生日期 的本地化字符串。
        /// </summary>
        public static string PersonViewModelBirthdayDisplayName {
            get {
                return ResourceManager.GetString("PersonViewModelBirthdayDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名字 的本地化字符串。
        /// </summary>
        public static string PersonViewModelNameDisplayName {
            get {
                return ResourceManager.GetString("PersonViewModelNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string PersonViewModelSexDisplayName {
            get {
                return ResourceManager.GetString("PersonViewModelSexDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName}不符合指定的条件 的本地化字符串。
        /// </summary>
        public static string predicate_error {
            get {
                return ResourceManager.GetString("predicate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName}格式不正确 的本地化字符串。
        /// </summary>
        public static string regex_error {
            get {
                return ResourceManager.GetString("regex_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string RoleViewModelIndexIDDisplayName {
            get {
                return ResourceManager.GetString("RoleViewModelIndexIDDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名称 的本地化字符串。
        /// </summary>
        public static string RoleViewModelIndexNameDisplayName {
            get {
                return ResourceManager.GetString("RoleViewModelIndexNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户类型 的本地化字符串。
        /// </summary>
        public static string RoleViewModelIndexTypeDisplayName {
            get {
                return ResourceManager.GetString("RoleViewModelIndexTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName}不能超过{expectedPrecision}位 的本地化字符串。
        /// </summary>
        public static string scale_precision_error {
            get {
                return ResourceManager.GetString("scale_precision_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName}的长度是{MinLength}-{MaxLength}个字符 的本地化字符串。
        /// </summary>
        public static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
    }
}
